#!/bin/bash

# image file -> block device
# for mount linux kernel image file.
# by steve jeong.

BLOCK="$(sudo losetup -f)"
TOP_PATH="$( cd "$(dirname $0)" ; pwd -P)"

[ ! -d tmp ] && mkdir -p tmp
read -r -p "Target Image file:" img
sudo losetup ${BLOCK} ${img} # delete: sudo losetup -d ${BLOCK}
sudo partx -v --add ${BLOCK}

echo "..."
echo "..."
echo "===================================="
echo "Complete losetup image file"
echo ""
echo "Usage:"
echo ""
echo "    mount \"${BLOCK}p#\" $(pwd)/tmp"
echo "===================================="

# vim: ft=sh ts=2 sw=2 sts=2 et
