#!/bin/bash

# Copyright (C) 2024 Steve Jeong <steve@how2flow.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>

PREFIX="/usr/share/kernel-scripts"
FIXUPS=${PREFIX}/fixups

options=$(getopt -o cfhil -l crosscompile,ftrace,help,install,losetup -- "$@")
eval set -- "${options}"

Usage() {
  echo "Usage: kernel-script [OPTIONS]"
  echo "Options:"
  echo "  -c, --crosscompile   Perform a cross-compilation of the kernel"
  echo "  -f, --ftrace         Run ftrace with kernel APIs"
  echo "                       need root permission"
  echo "  -l, --losetup        Losetup in loop devices"
  echo "                       need root permission"
  echo "  --help               Display this help message"
  exit 0
}

Run_with_menu() {
  local param=""

  . ${PREFIX}/menu
  menu_main
  if [ ! -z ${TO_DO} ]; then
    menu_config ${PREFIX} ${FIXUPS}
  fi

  param="with-menu"

  while true; do
    case ${TO_DO} in
      do_crosscompile)
        . ${FIXUPS}/do_crosscompile ${param}
        break
        ;;
      do_ftrace)
        . ${FIXUPS}/do_ftrace ${param}
        break
        ;;
      *)
        break
        ;;
    esac
  done
}

main() {
  local param=""

  param="with-option"

  while true; do
    case ${1} in
      -c|--crosscompile)
        . ${FIXUPS}/do_crosscompile ${param}
        break
        ;;
      -f|--ftrace)
        . ${FIXUPS}/do_ftrace ${param}
        break
        ;;
      -h|--help)
        Usage
        break
        ;;
      *)
        Run_with_menu
        break
        ;;
      --) shift
        break
        ;;
    esac
    shift
  done
}

main ${1}

# vim: set ft=sh ts=2 sw=2 sts=2 et
