#!/bin/bash

DEFAULT="/usr/share/kernel-scripts"
PREFIX=${CHECKOUT:-${DEFAULT}}

options=$(getopt -o cfhil -l crosscompile,ftrace,help,install,losetup -- "$@")
eval set -- "${options}"

Usage() {
  echo "Usage: kernel-script [OPTIONS]"
  echo "Options:"
  echo "  -c, --crosscompile   Perform a cross-compilation of the kernel"
  echo "  -f, --ftrace         Run ftrace with kernel APIs"
  echo "                       need root permission"
  echo "  -l, --losetup        Losetup in loop devices"
  echo "                       need root permission"
  echo "  --help               Display this help message"
  exit 0
}

while true; do
  case "$1" in
    -c|--crosscompile)
      . "${PREFIX}"/do_crosscompile
      exit 0
      ;;
    -f|--ftrace)
      . "${PREFIX}"/do_ftrace
      exit 0
      ;;
    -h|--help)
      Usage
      ;;
    -l|--losetup)
      . "${PREFIX}"/do_losetup
      exit 0
      ;;
    --) shift
      break
      ;;
    *)
      echo "Not implemented: $1" >&2
      ;;
  esac
  shift
done

# vim: set ft=sh ts=2 sw=2 sts=2 et
