#!/bin/bash

# image file -> block device
# for mount linux kernel image file.
# written by Steve Jeong (how2soft@gmail.com).

set -e

TOP_PATH="$(pwd -P)"
BLOCK="$(sudo losetup -f)"

[ ! -d tmp ] && mkdir -p tmp
read -r -p "Target Image file:" img
sudo losetup ${BLOCK} ${img} # delete: losetup -d ${BLOCK}
sudo partx -v --add ${BLOCK}

echo "..."
echo "..."
echo "===================================="
echo "Complete losetup image file"
echo ""
echo "Usage:"
echo ""
echo "    mount \"${BLOCK}p#\" $(pwd)/tmp"
echo "===================================="

# vim: ft=sh ts=2 sw=2 sts=2 et
