#!/bin/bash

# for install linux kernel (native).
# this script has to move in kernel's top path.
# written by Steve Jeong.

# path
TOP_PATH="$( cd "$(dirname $0)" ; pwd -P)"
OUT_PATH=${TOP_PATH}/out

echo "set architecture"
ARCH=$(dpkg --print-architecture)
case ${ARCH} in
  arm|armhf)
  ARCH=arm
  ;;
  arm64)
  ARCH=arm64
  ;;
esac

KERNEL=vmlinuz-$(cat ${OUT_PATH}/include/config/kernel.release)

echo "[kernel install]"
cd ${OUT_PATH}
sudo make modules_install
sudo make install # then, copy ${OUT_PATH}/arch/${ARCH}/boot/${image_file} to /boot

# vim: ft=sh ts=2 sw=2 sts=2 et
