#!/bin/bash

# for install linux kernel (native).
# this script has to move in kernel's top path.
# written by Steve Jeong (how2soft@gmail.com).

set -e

# path
TOP_PATH="$(pwd -P)"
OUT_PATH=${TOP_PATH}/out

echo "set architecture"
architecture=$(dpkg --print-architecture)
case ${architecture} in
  arm|armhf)
  ARCH=arm
  ;;
  arm64)
  ARCH=arm64
  ;;
esac

echo "[kernel install]"
cd ${OUT_PATH}
make modules_install
make install

# vim: ft=sh ts=2 sw=2 sts=2 et
